/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50:  '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7e22ce',
          800: '#6b21a8',
          900: '#581c87',
        },
      },
      fontFamily: {
        sans:    ['Inter', 'sans-serif'],
        display: ['Poppins', 'sans-serif'],
      },
      animation: {
        'fade-in':      'fadeIn 0.35s ease both',
        'slide-up':     'slideUp 0.4s cubic-bezier(0.34,1.56,0.64,1) both',
        'slide-down':   'slideDown 0.35s ease both',
        'slide-right':  'slideInRight 0.35s ease both',
        'scale-in':     'scaleIn 0.3s cubic-bezier(0.34,1.56,0.64,1) both',
        'pulse-slow':   'pulse-slow 2s ease-in-out infinite',
        'float':        'float 3s ease-in-out infinite',
        'spin-slow':    'spin-slow 8s linear infinite',
        'ping-slow':    'ping-slow 2s cubic-bezier(0,0,0.2,1) infinite',
        'gradient':     'gradient-x 4s ease infinite',
        'count-up':     'countUp 0.5s ease both',
        'border-pulse': 'borderPulse 2s ease-in-out infinite',
        'shimmer':      'shimmer 1.5s infinite',
      },
      keyframes: {
        fadeIn:       { from:{ opacity:'0' },                           to:{ opacity:'1' } },
        slideUp:      { from:{ transform:'translateY(24px)',opacity:'0'}, to:{ transform:'translateY(0)',opacity:'1' } },
        slideDown:    { from:{ transform:'translateY(-24px)',opacity:'0'},to:{ transform:'translateY(0)',opacity:'1' } },
        slideInRight: { from:{ transform:'translateX(24px)',opacity:'0'}, to:{ transform:'translateX(0)',opacity:'1' } },
        scaleIn:      { from:{ transform:'scale(0.92)',opacity:'0' },    to:{ transform:'scale(1)',opacity:'1' } },
        'pulse-slow': { '0%,100%':{ opacity:'1' }, '50%':{ opacity:'0.5' } },
        float:        { '0%,100%':{ transform:'translateY(0px)' }, '50%':{ transform:'translateY(-8px)' } },
        'spin-slow':  { from:{ transform:'rotate(0deg)' }, to:{ transform:'rotate(360deg)' } },
        'ping-slow':  { '0%':{ transform:'scale(1)',opacity:'1' }, '75%,100%':{ transform:'scale(1.5)',opacity:'0' } },
        'gradient-x': { '0%,100%':{ backgroundPosition:'0% 50%' }, '50%':{ backgroundPosition:'100% 50%' } },
        countUp:      { from:{ opacity:'0',transform:'translateY(8px)' }, to:{ opacity:'1',transform:'translateY(0)' } },
        borderPulse:  { '0%,100%':{ borderColor:'rgba(168,85,247,0.3)' }, '50%':{ borderColor:'rgba(168,85,247,0.8)' } },
        shimmer:      { '0%':{ backgroundPosition:'-200% 0' }, '100%':{ backgroundPosition:'200% 0' } },
      },
      backgroundSize: {
        '200': '200% 200%',
      },
      boxShadow: {
        'primary':  '0 4px 20px rgba(168,85,247,0.35)',
        'primary-lg':'0 8px 40px rgba(168,85,247,0.45)',
        'glow-green':'0 0 20px rgba(16,185,129,0.4)',
        'glow-red':  '0 0 20px rgba(239,68,68,0.4)',
        'glow-blue': '0 0 20px rgba(59,130,246,0.4)',
      },
    },
  },
  plugins: [],
}
